[package]
name = "whitehole-bench"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
in_str = "0.1.1"
whitehole = "0.5.0"
nom = "8.0.0"

[[bench]]
name = "json_lexer"
harness = false
